### ISSUE TITLE
ошибка если нет файла .babelrc в корне

### ISSUE THREAD

**Issue by eddyLazar** [tars/tars#193]
Если нет файла в корне, при этом флаг `useBabel`:`false`
выдает ошибку 
```
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/eddy/src/work/yoga/.babelrc'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.readFileSync (/usr/local/lib/node_modules/tars-cli/node_modules/jsonfile/index.js:31:20)
    at updateBabelConfig (/usr/local/lib/node_modules/tars-cli/lib/command-actions/utils/update-babelrc.js:11:33)
    at Object.dev (/usr/local/lib/node_modules/tars-cli/lib/command-actions/dev.js:82:5)
    at /usr/local/lib/node_modules/tars-cli/lib/get-cli-root.js:22:22
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)```

**Comment by artem-malko** [comment]
@eddyLazar расскажи, пожалуйста, что запускал, что делал?

**Comment by eddyLazar** [comment]
Да ничего такого, просто в одном проекте так же запускатеся вебпак, которому этот файл не нужен, я его удалил потом как обычно запустился тарс `tars dev` например и выкинулно эту ошибку. Просто  учитывая что в конфигах тарса babel выключен, то `.babelrc` по идее не должен быть нуженю
Сам тарс голый последней версии.

**Comment by artem-malko** [comment]
@eddyLazar так, понял в чем проблема. Пока верни его обратно, после фикса сможешь удалить. Как фикс выпущу, я тебя тут заменьшиню.

**Comment by eddyLazar** [comment]
спс

**Comment by artem-malko** [comment]
Ошибка касается TARS-CLI.

**Comment by artem-malko** [comment]
@eddyLazar на бою. Сделал еще так, чтобы babel-preset не ставился, если babel не юзается.
