### ISSUE TITLE
Error: Package comment-json is not available.

### ISSUE THREAD

**Issue by LitvinenkoEvgeny** [tars/tars#262]
ubuntu 14.04
на любую команду tars cli реагирует одинаково:

---------------------------------------------------------------------------------
'It seems, that TARS in current project is not compatible with current TARS-CLI!'
'Package "comment-json" is not available.'
'Update TARS-CLI via "tars update" and your project via "tars update-project"'
'Please, write to the tars.builder@gmail.com, if update did not help you.'
---------------------------------------------------------------------------------

tars update && tars update-project 
приводят к тому же результату

**Comment by artem-malko** [comment]
@LitvinenkoEvgeny полная переустановка tars-cli помогает? Приложите, пожалуйста, файл со стэктрейсом из npm

**Comment by artem-malko** [comment]
Переоткрою, если будет обратная связь.

**Comment by realainov** [comment]
У меня данная ошибка.

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'comment-json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.tarsRequire [as require] (D:\Frontend Development\Projects\tars-template-master\tars\tars.js:38:12)
    at Object.<anonymous> (D:\Frontend Development\Projects\tars-template-master\tars\helpers\plugins-config-processing.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)

Это если запускать gulp. Если запускать tars, то он виснет

gulp[10064]: c:\ws\src\node_contextify.cc:640: Assertion `args[1]->IsString()' failed.
 1: 00007FF77B4CF43A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4618
 2: 00007FF77B47D186 uv_loop_fork+86646
 3: 00007FF77B47D233 uv_loop_fork+86819
 4: 00007FF77B4848E8 uv_loop_fork+117208
 5: 00007FF77BAE549F v8::internal::PassesFilter+847
 6: 00007FF77BAE66D7 v8::internal::PassesFilter+5511
 7: 00007FF77BAE594C v8::internal::PassesFilter+2044
 8: 00007FF77BAE586B v8::internal::PassesFilter+1819
 9: 0000035D6A750481
