### ISSUE TITLE
Error: Cannot find module 'comment-json' при попытке запуска пользовательского таска в терминале

### ISSUE THREAD

**Issue by epicfail169** [tars/tars#316]
Заранее извиняюсь, возможно я чтото не понял с пользовательскими тасками.
Мне нужна возможность вызвать пользовательский таск в с помощью терминала.

На примере дефолтного \user-tasks\example-task.js, который присутствует в проекте при его инициализации. Если прописать в терминале gulp task-name то вываливается эта ошибка:

Error: Cannot find module 'comment-json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.tarsRequire [as require] (projectname\tars\tars.js:38:12)
    at Object.<anonymous> (projectname\tars\helpers\plugins-config-processing.js:3:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by epicfail169** [comment]
Решение нашел тут: https://github.com/tars/tars-cli/issues/11
Хорошо бы было упомянуть об этом в доках.

**Comment by artem-malko** [comment]
@epicfail169 не совсем понял, про что идет речь? В доках к tars-cli есть раздел про запуск своих тасков.

**Comment by Timures** [comment]
> Решение нашел тут: [tars/tars-cli#11](https://github.com/tars/tars-cli/issues/11)
> Хорошо бы было упомянуть об этом в доках.

-- Приветствую, столкнулся с этой проблемой, как вам удалось ее решить?
Прошел по ссылке [tars/tars-cli#11](https://github.com/tars/tars-cli/issues/11) , но не нашел решения
