### ISSUE TITLE
After updating Node, TARS does not work 

### ISSUE THREAD

**Issue by Solunsky** [tars/tars#336]
После обновления Node, TARS больше не работает вообще.
Ссылается на проблемы в sass, не загружает пакеты из user-package.json
Обновил node потому что он просто банально перестала работать команда npm install и все...

Даже откатил до старой версии Node 6, но...

```
RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\OSPanel\frontend\project\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by mshlmv** [comment]
node-sass переустановите

**Comment by movasyl** [comment]
Было что-то подобное. На сколько я понял, проблема не в ноде, а в новом npm.
1. Удалил TARS cli.
2. Откатил до 6 Ноды vs npm 3 ... что-то там ... что-то там
3. Установил TARS cli заново.
4. Обновился до последней ноды.
Все работает как по маслу.

**Comment by artem-malko** [comment]
Fixed in 1.9.8
