### ISSUE TITLE
Package gulp-sass is not available.

### ISSUE THREAD

**Issue by Selnapenek** [tars/tars#371]
Встречается такое на 
node-v8.12.0 ,  
TARS-CLI version: "1.10.3"
TARS version in current project: "1.10.0
При запуске дефолтного проекта.
На 6-ой ноде нормально все работает. macOS Sierra.
Не хочется постоянно переключаться с 8-ой на 6-ую ноду. Подскажите пожалуйста что можно сделать?
```
[01:59:18] Starting 'css:compile-css'...


---------------------------------------------------------------------------------
'It seems, that TARS in current project is not compatible with current TARS-CLI!'
'Package "gulp-sass" is not available.'
'Update TARS-CLI via "tars update" and your project via "tars update-project"'
'Please, write to the tars.builder@gmail.com, if update did not help you.'
---------------------------------------------------------------------------------

[01:59:18] 'css:compile-css' errored after 41 ms
[01:59:18] Error: Package gulp-sass is not available.
    at Object.tarsRequire [as require] (/Users/student/Documents/webProjects/tmp/tars/tars.js:34:19)
    at Object.preprocessor (/Users/student/Documents/webProjects/tmp/tars/tars.js:237:38)
    at generateTaskContent (/Users/student/Documents/webProjects/tmp/tars/tasks/css/helpers/concat-compile-css-task-template.js:177:31)
    at Gulp.tars.packages.gulp.task (/Users/student/Documents/webProjects/tmp/tars/tasks/css/compile-css.js:8:111)
    at module.exports (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/usr/local/lib/node_modules/tars-cli/node_modules/run-sequence/index.js:124:15)
    at Gulp.onTaskEnd (/usr/local/lib/node_modules/tars-cli/node_modules/run-sequence/index.js:102:4)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:264:8)
    at /Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/lib/runTask.js:29:3)
    at Promise.resolve.then.then.then (/Users/student/Documents/webProjects/tmp/tars/tasks/css/helpers/actions-on-sprite-task-skipping.js:37:21)
    at <anonymous>:null:null

[01:59:18] 'main:build-dev' errored after 464 ms
[01:59:18] Error in plugin "run-sequence(css:compile-css)"
Message:
    Package gulp-sass is not available.
Stack:
Error: Package gulp-sass is not available.
    at Object.tarsRequire [as require] (/Users/student/Documents/webProjects/tmp/tars/tars.js:34:19)
    at Object.preprocessor (/Users/student/Documents/webProjects/tmp/tars/tars.js:237:38)
    at generateTaskContent (/Users/student/Documents/webProjects/tmp/tars/tasks/css/helpers/concat-compile-css-task-template.js:177:31)
    at Gulp.tars.packages.gulp.task (/Users/student/Documents/webProjects/tmp/tars/tasks/css/compile-css.js:8:111)
    at module.exports (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/usr/local/lib/node_modules/tars-cli/node_modules/run-sequence/index.js:124:15)
    at Gulp.onTaskEnd (/usr/local/lib/node_modules/tars-cli/node_modules/run-sequence/index.js:102:4)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:264:8)
    at /Users/student/Documents/webProjects/tmp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/student/Documents/webProjects/tmp/node_modules/orchestrator/lib/runTask.js:29:3)
    at Promise.resolve.then.then.then (/Users/student/Documents/webProjects/tmp/tars/tasks/css/helpers/actions-on-sprite-task-skipping.js:37:21)
    at <anonymous>:null:null
```

**Comment by artem-malko** [comment]
Переустановить tars-cli. Это точно поможет

**Comment by Selnapenek** [comment]
Ах да, при переустановке вспомнил почему тарс на 6 ноде работает, на 8 phantomjs не устанавливается.

**Comment by lenchik-ponchik** [comment]
@Selnapenek Установи глобально с флагом --unsafe-perm. Заведется и на 10 и на 11 ноде. 
`sudo npm install -g tars-cli --unsafe-perm`
