### ISSUE TITLE
Тарс перестает устанавливаться

### ISSUE THREAD

**Issue by BjornSkarsgard** [tars/tars#425]
Накатил свежую винду, установил VS installer со всеми вытекающими и при установки тарса вечная ошибка с node-gyp. 
Собственно вот все что происходит в консоли после попытки установить тарс. Испробовал почти все возможные пути решения проблемы, но не могу решить ее.

___________________________________________________________________

npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated gulp-util@0.0.1: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated eslint-loader@3.0.4: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated request@2.67.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated mkdirp@0.5.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

npm ERR! code 1
npm ERR! path C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\WEB\skardev.v2\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\WEB\\skardev.v2\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\WEB\skardev.v2\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\WEB\skardev.v2\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\WEB\skardev.v2\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2.7 Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\WEB\skardev.v2\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\WEB\skardev.v2\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\WEB\skardev.v2\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python2.7". checking python launcher
npm ERR! gyp verb could not find "python2.7". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\WEB\skardev.v2\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\WEB\skardev.v2\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\WEB\skardev.v2\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WEB\\skardev.v2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:

**Comment by TolyanDimov** [comment]
Как вариант, попробуйте понизить версию npm `npm i npm@6.14.11 -g`

**Comment by artem-malko** [comment]
Я бы еще добавил, что стоит попробовать на nodejs 14 или 12

**Comment by bukhalo** [comment]
Попробуйте развернуть проект на свежих версиях `tars` и `tars-cli` на NodeJS v16. В крайнем релизе я оставил поддержку только v16 и избавился от зависимости `node-sass` из за которой было большинство проблем на разных версиях NodeJS и разных ОС.

**Comment by schiZis** [comment]
@bukhalo неужели это свершилось и мне больше не нужно извращаться с nvm. 
есть опыт переноса проектов, которые писались на старом тарсе, на новую версию?

**Comment by bukhalo** [comment]
@schiZis к сожалению или к счастью, у меня на данный момент нет проектов на тарсе (если будет лишний - поделитесь, пригодится для тестов). Я скорее мимокрокодил и готов что-нибудь сделать, потому что жалко хоронить проект.

**Comment by schiZis** [comment]
@bukhalo последние реализованные/текущие проекты по юридическим соображениям я отправить не могу. Поищу что-нибудь старое или то, от чего уже отказались, и что стабильно работала на тарсе под 14 нодой. 
Вчера при попытке инициализации сборщика в режиме разработки проекта с прежней версии тарса ожидаемо выплюнуло немного ошибок, пока в них не копался, но не могу ручаться, что это не по причине того, что что-либо кастомилось.

**Comment by artem-malko** [comment]
@schiZis можно попробовать в папке с проектом выполнить 
```sh
tars update-project
```

Ну и нода должна быть 16 и выше.

**Comment by schiZis** [comment]
@artem-malko а слона-то я и не заметил. 
апдейт помог, немного подправил то, на что ругался compile-css и всё заработало.
Большое спасибо за совет и прекрасный сборщик

**Comment by artem-malko** [comment]
@schiZis пользуйтесь на здоровье)

А что подправил в compile-css, если не секрет?

**Comment by schiZis** [comment]
@artem-malko видимо неверно выразился. Поправил ворнинги в scss-коде, на которые ругался compile-css. Возникли из-за перехода сборщика на dart sass. По типу нельзя использовать выражение "variable / n",  теперь "calc(variable / 2)". 
И почему-то при первом сборе не обработал переназначенный контейнер bootstrap, но очистка кэша решила ситуацию, так что видимо предыдущие инициализации сборки, которые завершались ошибкой умудрились каким-то образом закэшироваться.

**Comment by artem-malko** [comment]
@schiZis понял)

**Comment by artem-malko** [comment]
@bukhalo что думаешь, пока подержим issue открытым?)

**Comment by bukhalo** [comment]
@artem-malko ага, можно. Наверняка ещё у кого будут вопросы, кто не успел обновиться

**Comment by Solunsky** [comment]
Пришлите хотябы какую то инструкцию или сборку, которая работала от 16 node и выше, а то я совсем не понимаю как обновить tars, из за этого не могу перейти с node 14 версии
