### ISSUE TITLE
Errors while image saving in photoshop

### ISSUE THREAD

**Issue by teplenin** [tars/tars#83]
http://prntscr.com/7255zq такая ошибка возникает при сохранении картинки в фотошопе. Фотошоп создает .tmp файл и gulp вылетает, когда пытается его обработать. Возможно сделать проверку расширения перед обработкой?

**Comment by artem-malko** [comment]
@teplenin баг еще воспроизводится? Пытаемся повторить и все работает.

**Comment by teplenin** [comment]
Примерно 2 раза из 10 появляется эта ошибка

**Comment by artem-malko** [comment]
@teplenin а какая версия tars и какая ОС?

**Comment by teplenin** [comment]
Windows 7, 8.1, 10 - tars - последняя версия

**Comment by artem-malko** [comment]
@teplenin 1.2.7, верно?

**Comment by teplenin** [comment]
Верно

**Comment by artem-malko** [comment]
@teplenin а какая версия фотошопа? Сейчас еще мой коллега подключится @alexHlebnikov

**Comment by teplenin** [comment]
Photoshop CC x64, на работе Photoshop CS4

**Comment by artem-malko** [comment]
@teplenin и там, и там баг повторяется?

**Comment by artem-malko** [comment]
@teplenin и еще, можешь описать точную последовательность действий для повторения бага.

**Comment by teplenin** [comment]
Да. Разницы нет. Фотошоп сохраняет сначала временную версию файла, потом конвертирует. TARS подхватывает временный файл и выдает ошибку

**Comment by teplenin** [comment]
Сохраняю через "Сохранить для Web"

**Comment by alexHlebnikov** [comment]
@teplenin спасибо, смог воспроизвести, буду разбираться.

**Comment by artem-malko** [comment]
@teplenin Ну все, чиним) В 1.3.0 не будет такого)

**Comment by teplenin** [comment]
Рад помочь

**Comment by alexHlebnikov** [comment]
@teplenin заинить проект через cli: 
````bash
tars init -s https://github.com/tars/tars/archive/version-1-3-0-add-tmp-to-ignored.zip
````
и проверь, пожалуйста, пофиксилось или нет.

**Comment by teplenin** [comment]
http://i.imgur.com/olJIXwr.png

**Comment by teplenin** [comment]
Ничего не изменилось, создал новый проект

**Comment by alexHlebnikov** [comment]
@teplenin странно, вот эти правки https://github.com/tars/tars/pull/110 пофиксили проблему у меня на винде. Можешь попробовать посмотреть изменения в файлах и моего ПР (https://github.com/tars/tars/pull/110) и попробовать поправить для себя? 
Еще есть подозрение, что это баг chokidar. Можешь попробовать обновить его до последней версии и скажи на какой версии воспроизводится проблема?

**Comment by teplenin** [comment]
На рабочем компьютере вобще не запускается тарс


$ tars dev -t

[ TARS ]: Development task has been started!

[ TARS ]: Build options (active are green):
[ TARS ]: ✓ Server for tunnel and livereload will be started.
[ TARS ]: Server for livereload will be started "-l".
[ TARS ]: IE8 maintenance "--ie8".
[ TARS ]: IE9 maintenance "--ie9".
[ TARS ]: IE8 and IE9 maintenance "--ie".
[ TARS ]: Custom flags. "--custom-flags" 'customFlags, with space separator'


[ TARS ]: Execute "tars dev --help", to see all avaliable options.
[ TARS ]: You can use interactive mode via starting tars without any flags.
[ TARS ]: Please wait for a moment, while I'm preparing builder for working...

D:\Проекты\tst\gulpfile.js:41
    require(file)();
                 ^
TypeError: object is not a function
  at D:\Проекты\tst\gulpfile.js:41:18
  at Array.forEach (native)
  at Object.<anonymous> (D:\Проекты\tst\gulpfile.js:40:28)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\bin\gulp.js:116:3)
  at Liftoff.<anonymous> (C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\index.js:192:16)
  at module.exports (C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
  at Liftoff.<anonymous> (C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\index.js:185:9)
  at C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\index.js:159:9
  at C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\v8flags\index.js:99:14
  at C:\Users\Димасик\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\v8flags\index.js:38:7
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by teplenin** [comment]
Установил еще раз, результат другой

$ tars dev -l

[ TARS ]: Development task has been started!

[ TARS ]: Build options (active are green):
[ TARS ]: Server for tunnel and livereload will be started "-t".
[ TARS ]: ✓ Server for livereload will be started.
[ TARS ]: IE8 maintenance "--ie8".
[ TARS ]: IE9 maintenance "--ie9".
[ TARS ]: IE8 and IE9 maintenance "--ie".
[ TARS ]: Custom flags. "--custom-flags" 'customFlags, with space separator'


[ TARS ]: Execute "tars dev --help", to see all avaliable options.
[ TARS ]: You can use interactive mode via starting tars without any flags.
[ TARS ]: Please wait for a moment, while I'm preparing builder for working...

[10:43:09] Using gulpfile C:\Projects\tars\gulpfile.js
[10:43:09] Starting 'build-dev'...
[10:43:09] 'build-dev' errored after 521 μs
[10:43:09] Error: Task css:make-sprite-for-svg is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).

**Comment by artem-malko** [comment]
@teplenin нужно выполнить tars init

**Comment by teplenin** [comment]
Пробовал. И init и re-init. Оба выдают ошибки.

tars-config.js пробовал удалять

**Comment by teplenin** [comment]
tars init

[ TARS ]: Directory "C:\Projects\tars" is not empty.
? What would you like to do? (Use arrow keys)
> Clear current directory
  Create new directory for project
  Stop init

C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:75
    throw e;
          ^
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)

**Comment by teplenin** [comment]
Вернул файлы tars.json и tars-config.js и сделал re-init:

$ tars re-init


[ TARS ]: Reinitialization task has been started!

[ TARS ]: Please, answer some questions:

? What preprocessor for CSS do you want to use? (Use arrow keys)
> scss
  less
  stylus

C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:75
    throw e;
          ^
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)

**Comment by artem-malko** [comment]
@teplenin видимо винда. tars re-init --silent
Есть проблема с модулем интерфейса

**Comment by teplenin** [comment]
tars re-init --silent


[ TARS ]: Reinitialization task has been started!

D:\Проекты\tars\gulpfile.js:41
    require(file)();
                 ^
TypeError: object is not a function
  at D:\Проекты\tars\gulpfile.js:41:18
  at Array.forEach (native)
  at Object.<anonymous> (D:\Проекты\tars\gulpfile.js:40:28)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\bin\gulp.js:116:3)
  at Liftoff.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\index.js:192:16)
  at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
  at Liftoff.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\index.js:185:9)
  at C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\liftoff\index.js:159:9
  at C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\v8flags\index.js:99:14
  at C:\Users\user\AppData\Roaming\npm\node_modules\tars-cli\node_modules\gulp\node_modules\v8flags\index.js:38:7
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by artem-malko** [comment]
@teplenin а какая версия TARS? Можешь прислать gulpfile свой?

**Comment by teplenin** [comment]
Вот эта
https://github.com/tars/tars/archive/version-1-3-0-add-tmp-to-ignored.zip


gulpfile.js отправил на почту Артёму

**Comment by artem-malko** [comment]
@teplenin Хм, не могу сказать, что не так.
Обнови TARS по вот этому гайду https://github.com/tars/tars/blob/master/docs/ru/update-guide.md
Это точно поможет.

**Comment by teplenin** [comment]
Не обновляется. Всё ошибки выдает. 

Смысла, наверное, не обновлять? Он с нуля устанавливается с ошибками

**Comment by artem-malko** [comment]
@teplenin а с нуля опять ошибка типа: D:\Проекты\tars\gulpfile.js:41
require(file)();
^
TypeError: object is not a function
at D:\Проекты\tars\gulpfile.js:41:18 ?

**Comment by teplenin** [comment]
@artem-malko Да

**Comment by artem-malko** [comment]
@teplenin а можешь где-нибудь, в любом месте в gulpfile вывести require? console.log(require).
Такое ощущение, что require переопределен где-то.

**Comment by teplenin** [comment]
@artem-malko  Отправил на почту

**Comment by artem-malko** [comment]
@teplenin чертовщина какая-то... А можешь выслать весь проект без node_modules?

**Comment by teplenin** [comment]
Его скачал и разархивировал

https://github.com/tars/tars/archive/version-1-3-0-add-tmp-to-ignored.zip

**Comment by teplenin** [comment]
Пустой проект

**Comment by artem-malko** [comment]
@teplenin тогда назови, пожалуйста ОС, версию годы и все шаги, что ты делаешь, чтобы запустить проект.

**Comment by teplenin** [comment]
node последняя, ОС Win7 и Win10.

1. Скачал tars
2. Распаковал
3. Запустил консоль
4. gulp init
5. Ошибка

**Comment by teplenin** [comment]
Стабильная версия запускается

**Comment by artem-malko** [comment]
@teplenin то есть cli ты не использовал?

**Comment by teplenin** [comment]
tars init то же самое выдает

**Comment by artem-malko** [comment]
@teplenin хорошо, попробую все в выходные повторить.

**Comment by artem-malko** [comment]
@teplenin привет, забросил TARS уже?)

**Comment by teplenin** [comment]
@artem-malko Привет. Пока проектов новых нет, не работаю с ним

**Comment by artem-malko** [comment]
@teplenin а можешь проверить, повторяется ли баг в новых версиях?

**Comment by teplenin** [comment]
@artem-malko Не могу пока проверить. После обновления npm и node появилась ошибка

> $ npm install
> npm WARN install Couldn't install optional dependency: Unsupported

Это баг последнего npm, после исправления проверю tars

**Comment by artem-malko** [comment]
@teplenin а это аффектит установку?

**Comment by teplenin** [comment]
@artem-malko за минут 10 выдало 3 сообщения http://prntscr.com/8z8pg1
дожидаться окончания не стал

**Comment by artem-malko** [comment]
@teplenin А вот зря)

**Comment by teplenin** [comment]
@artem-malko Дальше ошибки идут

http://prntscr.com/8z9641

Это простая версия, не tars-cli

**Comment by artem-malko** [comment]
@teplenin это не влияет на установку. Просто у тебя Питона нет, и все. Но это не важно
